name: Generate and Upload SBOM

permissions: {}

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload SBOMs
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required by actions/checkout to read the repository

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install CycloneDX
      run: dotnet tool install --global CycloneDX

    - name: Generate SBOMs
      run: |
        dotnet CycloneDX OSMDataPrimitives/OSMDataPrimitives.csproj -o ./ --filename osm-data-primitives-sbom.xml
        dotnet CycloneDX OSMDataPrimitives.BSON/OSMDataPrimitives.BSON.csproj -o ./ --filename osm-data-primitives-bson-sbom.xml
        dotnet CycloneDX OSMDataPrimitives.Spatial/OSMDataPrimitives.Spatial.csproj -o ./ --filename osm-data-primitives-spatial-sbom.xml
    
    - name: Upload SBOM for OSMDataPrimitives to DependencyTrack
      env:
        DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
        DTRACK_URL: ${{ secrets.DTRACK_URL }}
      run: |
        curl -X "POST" \
            "${DTRACK_URL}/api/v1/bom" \
            -H "X-API-Key: ${DTRACK_API_KEY}" \
            -H "Content-Type: multipart/form-data" \
            -F "projectName=OSMDataPrimitives" \
            -F "bom=@osm-data-primitives-sbom.xml"

    - name: Upload SBOM for OSMDataPrimitives.BSON to DependencyTrack
      env:
        DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
        DTRACK_URL: ${{ secrets.DTRACK_URL }}
      run: |
        curl -X "POST" \
            "${DTRACK_URL}/api/v1/bom" \
            -H "X-API-Key: ${DTRACK_API_KEY}" \
            -H "Content-Type: multipart/form-data" \
            -F "projectName=OSMDataPrimitives.BSON" \
            -F "bom=@osm-data-primitives-bson-sbom.xml"

    - name: Upload SBOM for OSMDataPrimitives.Spatial to DependencyTrack
      env:
        DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
        DTRACK_URL: ${{ secrets.DTRACK_URL }}
      run: |
        curl -X "POST" \
            "${DTRACK_URL}/api/v1/bom" \
            -H "X-API-Key: ${DTRACK_API_KEY}" \
            -H "Content-Type: multipart/form-data" \
            -F "projectName=OSMDataPrimitives.Spatial" \
            -F "bom=@osm-data-primitives-spatial-sbom.xml"